### ISSUE TITLE
有点小期待项目投入生产

### ISSUE THREAD

**Issue by PLQin** [skywalker512/weibo-frontend#8]
期待展示链接

**Comment by PLQin** [comment]
issues 不适合做项目进度管理 , 不如试试其他栏目

**Comment by skywalker512** [comment]
抱歉，这个不会 投入生产，这个是我们学校的一个学生组织的寒假作业，它的目标是让我熟悉前端的知识，以及整个网站开发的流程，并没有做生产方面的考虑

我同时使用 Projects 来管理项目，但是只有我一个人开发，所以就拿 issue 来用了
